language: node_js

sudo: false

node_js:
  - "12.0.0"

install:
  - npm install

script:
  - npm run lint
  - npm run test

cache:
  directories:
    - $HOME/.npm
    - node_modules

services:
  - docker
